"""
core/cache_manager.py

Visibility and manual cleanup for the app's own generated/cached files -
everything EXCEPT downloaded VODs (DOWNLOADS_DIR). Those are the user's
actual editing source material, never offered for deletion here; the
existing downloads-folder override/Browse/Open controls are the right place
to manage them, not a cache-clearing button that could look like "safe to
reclaim space" when it very much isn't.

Every category here is either a pure cache (thumbnails, previews, RMS/
sound-event timelines) that regenerates silently and cheaply on next use,
or a fetch cache (subtitles, chat, Whisper transcripts) that regenerates by
re-fetching/re-transcribing - slower, but never a source of real data loss,
since the source VOD itself is untouched either way.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List

from config import (
    AUDIO_RMS_CACHE_DIR, CACHE_DIR, DOWNLOADS_DIR, PREVIEWS_DIR,
    SCRATCH_DIR, SOUND_EVENT_CACHE_DIR, THUMBNAILS_DIR,
)

logger = logging.getLogger(__name__)


def _files_in(path: Path) -> List[Path]:
    if not path.exists():
        return []
    return [p for p in path.rglob("*") if p.is_file()]


def _size_of(paths: Iterable[Path]) -> int:
    """Best-effort total size - a file vanishing mid-walk (e.g. a background job
    cleaning up its own scratch file right as this runs) is skipped, not an error."""
    total = 0
    for p in paths:
        try:
            total += p.stat().st_size
        except OSError:
            continue
    return total


def format_size(num_bytes: int) -> str:
    """Human-readable size, e.g. '482 KB', '1.3 GB'."""
    size = float(num_bytes)
    for unit in ("B", "KB", "MB"):
        if size < 1024:
            return f"{size:.0f} {unit}"
        size /= 1024
    return f"{size:.1f} GB"


def _clear(paths: Iterable[Path]) -> int:
    """Best-effort delete, mirrors core.session_store.purge_sessions exactly -
    logs and continues past individual failures rather than aborting partway
    through and leaving the user unsure what actually got removed."""
    removed = 0
    for p in paths:
        try:
            p.unlink()
            removed += 1
        except OSError as exc:
            logger.warning("Could not delete cache file '%s': %s", p, exc)
    return removed


def _srt_cache_files() -> List[Path]:
    return list(CACHE_DIR.glob("whisper_*.srt"))


def _subtitle_cache_files() -> List[Path]:
    return list(CACHE_DIR.glob("yt_*.vtt"))


def _chat_cache_files() -> List[Path]:
    return list(CACHE_DIR.glob("twitch_chat_*.json"))


def _fetch_cache_files() -> List[Path]:
    return _srt_cache_files() + _subtitle_cache_files() + _chat_cache_files()


@dataclass(frozen=True)
class CacheCategory:
    key: str
    label: str
    size_bytes: int
    file_count: int
    note: str


def get_breakdown() -> List[CacheCategory]:
    """
    Live-computed every call, same "never trust a stored flag, just check the
    real filesystem state" reasoning already used throughout this app
    (core.whisper_setup.detect_state, core.ollama_setup's live GPU/install
    checks) - there's nothing here expensive enough to justify caching the
    cache-size check itself.
    """
    previews_thumbs_files = _files_in(PREVIEWS_DIR) + _files_in(THUMBNAILS_DIR)
    analysis_files = _files_in(AUDIO_RMS_CACHE_DIR) + _files_in(SOUND_EVENT_CACHE_DIR)
    fetch_files = _fetch_cache_files()
    scratch_files = _files_in(SCRATCH_DIR)
    download_files = list(DOWNLOADS_DIR.glob("*.mp4"))

    return [
        CacheCategory(
            "downloads", "Downloaded VODs",
            _size_of(download_files), len(download_files),
            "Manage these from the Downloads folder controls above, not here.",
        ),
        CacheCategory(
            "previews", "Preview clips & thumbnails",
            _size_of(previews_thumbs_files), len(previews_thumbs_files),
            "Regenerated instantly the next time you preview or view a candidate.",
        ),
        CacheCategory(
            "analysis", "Audio & sound-event analysis cache",
            _size_of(analysis_files), len(analysis_files),
            "Regenerated by re-running analysis on the same VOD.",
        ),
        CacheCategory(
            "fetch", "Transcripts, subtitles & chat cache",
            _size_of(fetch_files), len(fetch_files),
            "Regenerated by re-fetching or re-transcribing - local Whisper "
            "transcripts in particular can take a while to redo.",
        ),
        CacheCategory(
            "scratch", "Leftover temp files",
            _size_of(scratch_files), len(scratch_files),
            "Should normally be empty - anything here is left over from an "
            "interrupted download, install, or transcription.",
        ),
    ]


def clear_previews_and_thumbnails() -> int:
    return _clear(_files_in(PREVIEWS_DIR) + _files_in(THUMBNAILS_DIR))


def clear_analysis_cache() -> int:
    return _clear(_files_in(AUDIO_RMS_CACHE_DIR) + _files_in(SOUND_EVENT_CACHE_DIR))


def clear_fetch_cache() -> int:
    return _clear(_fetch_cache_files())


def clear_scratch() -> int:
    return _clear(_files_in(SCRATCH_DIR))


def clear_all_except_downloads() -> int:
    """One button for the common case - reclaim everything reclaimable without
    ever touching the user's actual source videos."""
    return (
        clear_previews_and_thumbnails()
        + clear_analysis_cache()
        + clear_fetch_cache()
        + clear_scratch()
    )
